language: objective-c

osx_image: xcode8.3

before_script: 
  - cd iOS-Template/CodeDoesGood-iOSTemplate && pod plugins install cocoapods-keys && pod install
  - bundle exec pod keys set NetworkAPIToken $NETWORKAPITOKEN

script:
  - xcodebuild -version
  - xcodebuild -workspace CodeDoesGood-iOSTemplate.xcworkspace -scheme 'CodeDoesGood-iOSTemplate' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" test